# Site
name: "Nguoi Trong Van Phong"
title: "Nguoi Trong Van Phong"
description: "Hay subscribe cho Nguoi Trong Van Phong!"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  minh:
    name: Nguoi Trong Van Phong
    display_name: Nguoi Trong Van Phong
    avatar: 'assets/images/avatar.png'
    email: trantminh1754@protonmail.com
    web: https://www.youtube.com/c/nguoitrongvanphong?sub_confirmation=1
    twitter: https://www.youtube.com/c/nguoitrongvanphong?sub_confirmation=1
    description: ""
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
